version: '3.4'

networks:
  backend:

services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: ELECTRONICS_DB
      MYSQL_USER: USER
      MYSQL_PASSWORD: PASSWORD
    networks:
      - backend
    ports:
      - "3306:3306"
  electronicsdbapi:
    image: ${DOCKER_REGISTRY-}electronicsdbapi
    networks:
      - backend
    build:
      context: .
      dockerfile: ElectronicsDbApi/Dockerfile
